# The 'files' section is a mapping between the path of the file relative to
# the repository root and its location in the filesystem (where the program
# expects it)
# In this case, say your repository is at `~/.dotfiles`, it will map
# `~/.dotfiles/zsh/zprofile` to `~/.zprofile`
# and `~/.dotfiles/zshrc` to `~/.zshrc`
# 
# [zsh.files]
# "zsh/zprofile" = "~/.zprofile"
# zshrc = "~/.zshrc"

[bash.files]
"config/bash/config.sh" = "~/.bashrc"
