bar:
  height: 26
  location: top
  spacing: 20
  margin: 10

  foreground: f8f8f8ff
  background: 00000088

  font: DejaVu Sans Mono:pixelsize=14

  left:
    - river:
        anchors:
          - base: &river_base
              default: {string: {text: " # "}}
              conditions:
                id == 1: {string: {text: " 1 "}}
                id == 2: {string: {text: " 2 "}}  
                id == 3: {string: {text: " 3 "}}  
                id == 4: {string: {text: " 4 "}}  
                id == 5: {string: {text: " 5 "}}
                id == 6: {string: {text: " 6 "}}
                id == 7: {string: {text: " 7 "}}  
                id == 8: {string: {text: " 8 "}}  
                id == 9: {string: {text: " 9 "}}  

        content:
          map:
            on-click: 
              left: "sh -c 'riverctl set-focused-tags $((1 << ({id} - 1)))'"
              right: "sh -c 'riverctl toggle-focused-tags $((1 << ({id} -1)))'"
              middle: "sh -c 'riverctl toggle-view-tags $((1 << ({id} -1)))'"
            default:
              map:
                <<: *river_base
            conditions:
              state == focused:
                map:
                  <<: *river_base
                  deco: {background: {color: 80808088}}
              state == unfocused:
                map:
                  <<: *river_base
                  deco: {background: {color: 60606088}}
              state == invisible && ~occupied: 
                empty: {}
  center:
    - river:
        title: {string: {text: "{title}"}}
        content:
          - empty: {}
  right:
    - pipewire:
        content:
          string: {text: "{linear_volume}% on {form_factor}"}
    - network:
        name: "eno1"
        content:
          string: {text: "{state} @ {ipv4}"}
    - clock:
        time-format: "%H:%M:%S %z"
        date-format: "%Y-%m-%d"
        content:
          - string: {text: "{date} T {time}"}
