#!/bin/sh

# settings
mod=Mod1  # LAlt

riverctl keyboard-layout gb

riverctl spawn rivertile
riverctl default-layout rivertile

restart() { ( pkill $1; riverctl spawn $@ ) & }
start()   { ( ps -C $1 || riverctl spawn $@ ) & }

export SUDO_ASKPASS="/home/max/.config/tofi/scripts/askpass.sh"

# auto exec
start "udiskie"
restart "kanshi"
restart "waybar"  # restart "yambar" && sleep 0.1 && riverctl focus-output next  && riverctl spawn "yambar"
restart "~/.config/river/scripts/2_FHD_swaybg.sh"
start "pipewire"
start "wireplumber"
riverctl spawn "mpd --no-daemon"
start "wl-paste --type text --watch cliphist store"
start "wl-paste --type image --watch cliphist store"

# network mounts
sudo -A mount -t cifs -o credentials=/mnt/.athena,uid=1000,gid=1000 //192.168.0.25/auth /mnt/smb/athena/auth
sudo -A mount -t cifs -o credentials=/mnt/.athena,uid=1000,gid=1000 //192.168.0.25/music /mnt/smb/athena/music
sudo -A mount -t cifs -o credentials=/mnt/.athena,uid=1000,gid=1000 //192.168.0.25/notes /mnt/smb/athena/notes
sudo -A mount -t cifs -o credentials=/mnt/.athena,uid=1000,gid=1000 //192.168.0.25/setup /mnt/smb/athena/setup

sudo -A mount -t cifs -o credentials=/mnt/.fullimage,file_mode=0755,dir_mode=0755 //192.168.0.10/Media /mnt/smb/svr1/Media

sudo -A mount -t cifs -o credentials=/mnt/.fullimage,file_mode=0755,dir_mode=0755 //192.168.0.15/Public /mnt/smb/dc1/Public
sudo -A mount -t cifs -o credentials=/mnt/.fullimage,file_mode=0755,dir_mode=0755 //192.168.0.15/Technical /mnt/smb/dc1/Technical

# spawners
riverctl map normal $mod Q spawn "alacritty"
riverctl map normal $mod+Shift Q spawn "alacritty --class 'floating'"
riverctl map normal $mod B spawn "brave-browser-stable"
riverctl map normal $mod E spawn "nautilus"
riverctl map normal $mod R spawn "tofi-drun | xargs riverctl spawn"
riverctl map normal $mod+Shift R spawn "tofi-run | xargs riverctl spawn"
riverctl map normal $mod D spawn "~/.config/tofi/scripts/desktop_scripts.sh"
riverctl map normal $mod T spawn "~/.config/tofi/scripts/remote.sh"
riverctl map normal $mod A spawn "hyprpicker -anr"
riverctl map normal $mod Z spawn "swaylock"
riverctl map normal $mod+Shift Z spawn "~/.config/tofi/scripts/powermenu.sh"
riverctl map normal $mod V spawn "cliphist list | tofi | cliphist decode | wl-copy && wl-paste"

for mode in normal locked; do  # allows screenshots on lockscreen
  riverctl map $mode $mod S spawn 'riverctl spawn "grim -g \"$(slurp)\" $XDG_SCREENSHOTS_DIR/$(date +\"%s_grim.png\")"'
  riverctl map $mode $mod+Shift S spawn 'riverctl spawn "grim $XDG_SCREENSHOTS_DIR/$(date +\"%s_grim.png\")"'
done
  
# controls
riverctl map normal $mod Space toggle-float
riverctl map normal $mod Return toggle-fullscreen
riverctl map normal $mod C close
riverctl map normal $mod+Shift W spawn "~/.config/river/init"  # sort of reloads, but doesn't unset anything previously declared (just overwrites)
riverctl map normal $mod+Shift E exit

# media keys
for mode in normal locked; do
  riverctl map -repeat normal None KP_Home spawn "pamixer -d 5"
  riverctl map -repeat normal None KP_Up spawn "pamixer --toggle-mute"
  riverctl map -repeat normal None KP_Prior spawn "pamixer -i 5"
  riverctl map normal None KP_Left spawn "mpc prev"
  riverctl map normal None KP_Begin spawn "mpc toggle"
  riverctl map normal None KP_Right spawn "mpc next"
done

# move focus
riverctl map normal $mod Left focus-view previous
riverctl map normal $mod Right focus-view next

riverctl map normal $mod bracketleft focus-output previous
riverctl map normal $mod bracketright focus-output next

# move windows
riverctl map normal $mod+Shift Left swap previous
riverctl map normal $mod+Shift Right swap next

riverctl map-pointer normal $mod BTN_LEFT move-view

riverctl map normal $mod H move left 100
riverctl map normal $mod J move down 100
riverctl map normal $mod K move up 100
riverctl map normal $mod L move right 100

riverctl map normal $mod+Shift H move left 10
riverctl map normal $mod+Shift J move down 10
riverctl map normal $mod+Shift K move up 10
riverctl map normal $mod+Shift L move right 10

riverctl map normal $mod+Shift bracketleft spawn "riverctl send-to-output previous && riverctl focus-output previous"
riverctl map normal $mod+Shift bracketright spawn "riverctl send-to-output next && riverctl focus-output next"

# resize windows
riverctl map normal $mod U resize horizontal -10
riverctl map normal $mod I resize vertical -10
riverctl map normal $mod O resize vertical 10
riverctl map normal $mod P resize horizontal 10

riverctl map-pointer normal $mod BTN_RIGHT resize-view

# tags / workspaces
for i in $(seq 1 9); do
  tags=$((1 << ($i -1)))

  # focus tags [0-8]
  # ie, 'switch to workspace 1-9'
  riverctl map normal $mod $i set-focused-tags $tags

  # tag focused view with tag [0-8]
  # ie, 'move window to workspace 1-9'
  riverctl map normal $mod+Shift $i set-view-tags $tags
done

# window rules
riverctl float-filter-add app-id 'launcher'
riverctl float-filter-add app-id 'floating'
riverctl float-filter-add app-id "org.gnome.Nautilus"
riverctl float-filter-add app-id "org.gnome.Calculator"

# cleanup
riverctl spawn "notify-send 'River Init Loaded'"
