#!/bin/sh

# settings
mod=Mod1

riverctl keyboard-layout gb

riverctl spawn rivertile
riverctl default-layout rivertile

restart() { ( pkill $1; riverctl spawn $@ )>/dev/null 2>&1 & }
start()   { ( ps -C $1 || riverctl spawn $@ )>/dev/null 2>&1 & }

# auto exec
start "udiskie"
restart "kanshi"
restart "waybar"  # restart "yambar" && sleep 0.1 && riverctl focus-output next  && riverctl spawn "yambar"
restart "~/.config/river/scripts/2_FHD_swaybg.sh"
start "pipewire"
start "wireplumber"
start "wl-paste --type text --watch cliphist store"
start "wl-paste --type image --watch cliphist store"

# spawners
riverctl map normal $mod Q spawn "foot"
riverctl map normal $mod+Shift Q spawn "foot --app-id 'floating'"
riverctl map normal $mod B spawn "brave-browser-stable"
riverctl map normal $mod E spawn "nautilus"
riverctl map normal $mod R spawn "tofi-drun | xargs riverctl spawn"
riverctl map normal $mod+Shift R spawn "tofi-run | xargs riverctl spawn"
riverctl map normal $mod D spawn "~/.config/tofi/scripts/desktop_scripts.sh"
riverctl map normal $mod A spawn "hyprpicker -anr"
riverctl map normal $mod Z spawn "swaylock"
riverctl map normal $mod+Shift Z spawn "~/.config/tofi/scripts/powermenu.sh"
riverctl map normal $mod V spawn "cliphist list | tofi | cliphist decode | wl-copy && wl-paste"

for mode in normal locked; do
  riverctl map $mode $mod S spawn 'riverctl spawn "grim -g \"$(slurp)\" $XDG_SCREENSHOTS_DIR/$(date +\"%s_grim.png\")"'
  riverctl map $mode $mod+Shift S spawn 'riverctl spawn "grim $XDG_SCREENSHOTS_DIR/$(date +\"%s_grim.png\")"'
done
  
# controls
riverctl map normal $mod Space toggle-float
riverctl map normal None F11 toggle-fullscreen
riverctl map normal $mod C close
riverctl map normal $mod+Shift W spawn "~/.config/river/init"  # sort of reloads, but doesn't unset anything previously declared (just overwrites)
riverctl map normal $mod+Shift E exit

# media keys
for mode in normal locked; do
  riverctl map normal None KP_Home spawn "pamixer -d 5"
  riverctl map normal None KP_Up spawn "pamixer --toggle-mute"
  riverctl map normal None KP_Prior spawn "pamixer -i 5"
done

# move focus
riverctl map normal $mod Left focus-view previous
riverctl map normal $mod Right focus-view next

riverctl map normal $mod bracketleft focus-output previous
riverctl map normal $mod bracketright focus-output next

# move windows
riverctl map normal $mod+Shift Left swap previous
riverctl map normal $mod+Shift Right swap next

riverctl map-pointer normal $mod BTN_LEFT move-view

riverctl map normal $mod H move left 100
riverctl map normal $mod J move down 100
riverctl map normal $mod K move up 100
riverctl map normal $mod L move right 100

riverctl map normal $mod+Shift bracketleft spawn "riverctl send-to-output previous && riverctl focus-output previous"
riverctl map normal $mod+Shift bracketright spawn "riverctl send-to-output next && riverctl focus-output next"

# resize windows
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# tags / workspaces
for i in $(seq 1 9); do
  tags=$((1 << ($i -1)))

  # focus tags [0-8] with 1-9
  riverctl map normal $mod $i set-focused-tags $tags

  # tag focused view with tag [0-8]
  riverctl map normal $mod+Shift $i set-view-tags $tags
done

# window rules
riverctl float-filter-add app-id 'launcher'
riverctl float-filter-add app-id 'floating'
riverctl float-filter-add app-id "org.gnome.Nautilus"

# cleanup
riverctl spawn "notify-send 'River Init Loaded'"
