# The 'files' section is a mapping between the path of the file relative to
# the repository root and its location in the filesystem (where the program
# expects it)
# In this case, say your repository is at `~/.dotfiles`, it will map
# `~/.dotfiles/zsh/zprofile` to `~/.zprofile`
# and `~/.dotfiles/zshrc` to `~/.zshrc`
# 
# [zsh.files]
# "zsh/zprofile" = "~/.zprofile"
# zshrc = "~/.zshrc"

[bash.files]
"config/bash/config.sh" = "~/.bashrc"

[cava.files]
"config/cava/config.conf" = "~/.config/cava/config"

[dunst.files]
"config/dunst/config.conf" = "~/.config/dunst/dunstrc"

[glaze-wm]
depends = ["helix", "pwsh", "wt"]
[glaze-wm.files]
"config/glaze-wm/config.yaml" = "~/.glaze-wm/config.yaml"

[helix.files]
"config/helix/config.toml" = "~/.config/helix/config.toml"
"config/helix/themes" = "~/.config/helix/themes"

[hypr]
depends = ["bash", "dunst", "helix", "kitty", "ly", "rofi", "swaylock", "waybar"]
[hypr.files]
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprpaper.conf"
"config/hypr/hyprempty.toml" = "~/.config/hypr-empty/config.toml"

[kitty.files]
"config/kitty/config.conf" = "~/.config/kitty/config"
"config/kitty/curent-theme.conf" = "~/.config/kitty/current-theme.conf"
