# The 'files' section is a mapping between the path of the file relative to
# the repository root and its location in the filesystem (where the program
# expects it)
# In this case, say your repository is at `~/.dotfiles`, it will map
# `~/.dotfiles/zsh/zprofile` to `~/.zprofile`
# and `~/.dotfiles/zshrc` to `~/.zshrc`
# 
# [zsh.files]
# "zsh/zprofile" = "~/.zprofile"
# zshrc = "~/.zshrc"

[bash.files]
"config/bash/config.sh" = "~/.bashrc"

[cava.files]
"config/cava/config.conf" = "~/.config/cava/config"

[dunst.files]
"config/dunst/config.conf" = "~/.config/dunst/dunstrc"

[glaze-wm.files]
"config/glaze-wm/config.yaml" = "~/.glaze-wm/config.yaml"

[helix.files]
"config/helix/config.toml" = "~/.config/helix/config.toml"
"config/helix/themes" = "~/.config/helix/themes"

[hypr.files]
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprpaper.conf"
"config/hypr/hyprempty.toml" = "~/.config/hypr-empty/config.toml"

[kitty.files]
"config/kitty/config.conf" = "~/.config/kitty/config"
"config/kitty/curent-theme.conf" = "~/.config/kitty/current-theme.conf"

[ly.files]
"config/ly/config.ini" = "/etc/ly/config.ini"

# [pwsh.files]
# "config/pwsh/config.ps1" = ""

[pypoetry.files]
"config/pypoetry/config.toml" = "~/.config/pypoetry/config.toml"

# [rofi.files]
# 

[swaylock.files]
"config/swaylock/config" = "~/.config/swaylock/config"

[waybar.files]
"config/waybar/config.json" = "~/.config/waybar/config"
"config/waybar/style.css" = "~/.config/waybar/style.css"

[winfetch.files]
"config/winfetch/config.ps1" = "~/.config/winfetch/config.ps1"

[wt]
"config/wt/config.json" = "~/scoop/apps/windows-terminal/current/settings/settings.json"
