# global config location for `dotter`
# maps the files in the git repo to where the system expects them to be

[alacritty.files]
"config/alacritty/config.toml" = "~/.config/alacritty/alacritty.toml"
[alacritty.variables]
alacritty_sh_cmd = "{ program = 'bash', args = [] }"
alacritty_font = "{ family = 'Monospace', style = 'Regular' }"
alacritty_font_size = 12

[ash.files]
"config/ash/config.sh" = "~/.profile"

[bash.files]
"config/bash/config.sh" = "~/.bashrc"
"config/bash/aliases.sh" = "~/.bash/aliases.sh"
"config/bash/autostart.sh" = "~/.bash/autostart.sh"
"config/bash/variables.sh" = "~/.bash/variables.sh"

[cava]
depends = ["tmux"]
[cava.files]
"config/cava/averaged.ini" = "~/.config/cava/config"
"config/cava/stereo.ini" = "~/.config/cava/stereo"
"config/cava/left.ini" = "~/.config/cava/left"
"config/cava/right.ini" = "~/.config/cava/right"
"config/cava/scripts" = {target="~/.config/cava/scripts", type="symbolic", recurse=false}

[dunst.files]
"config/dunst/config.conf" = "~/.config/dunst/dunstrc"

[foot.files]
"config/foot/config.ini" = "~/.config/foot/foot.ini"

[glances.files]
"config/glances/config.ini" = "~/.config/glances/glances.conf"

[glaze-wm.files]
"config/glaze-wm/config.yaml" = "~/.glaze-wm/config.yaml"
"config/glaze-wm/scripts" = {target="~/.glaze-wm/scripts", type="symbolic", recurse=false}
"config/glaze-wm/scripts/autostart_wrapper.vbs" = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/autostart_wrapper.vbs"

[git.files]
"config/git/config.ini" = "~/.gitconfig"
[git.variables]
autocrlf = "input"
gh_path = "/usr/bin/gh"

[grub.files]
"config/grub/grub" = "/etc/default/grub"

[gtk.files]
"config/gtk-3.0/config.ini" = "~/.config/gtk-3.0/settings.ini"
"config/gtk-3.0/gtk.css" = "~/.config/gtk-3.0/gtk.css"

"config/gtk-4.0/config.ini" = "~/.config/gtk-4.0/settings.ini"
"config/gtk-4.0/gtk.css" = "~/.config/gtk-4.0/gtk.css"

[helix.files]
"config/helix/config.toml" = "~/.config/helix/config.toml"
"config/helix/themes" = {target="~/.config/helix/themes", type="symbolic", recurse=false}
[helix.variables]
helix_sh_cmd = "['bash']"

[kanshi.files]
"config/kanshi/config" = "~/.config/kanshi/config"

[irssi.files]
"config/irssi/config" = "~/.irssi/config"
"config/irssi/default.theme" = "~/.irssi/default.theme"
"config/irssi/scripts" = {target="~/.irssi/scripts", type="symbolic", recurse=false}
"config/irssi/startup" = "~/.irssi/startup"
"config/irssi/weed.theme" = "~/.irssi/weed.theme"

[mpd.variables]
mpd_host = "127.0.0.1"
music_path = "/music"
user_home = "~"
[mpd.files]
"config/mpd/config.conf" = "~/.config/mpd/mpd.conf"

[ncmpcpp.files]
"config/ncmpcpp/config.conf" = "~/.config/ncmpcpp/config"

[neofetch.files]
"config/neofetch/config.conf" = "~/.config/neofetch/config.conf"
[neofetch.variables]
disks = "'/boot/EFI' '/' '/home'"

[pwsh.files]
"config/pwsh/config.ps1" = "~/Documents/Powershell/Microsoft.Powershell_profile.ps1"  # doesn't work for roaming profiles
[pwsh.variables]
net_adapter = "WiFi"

[pypoetry.files]
"config/pypoetry/config.toml" = "~/.config/pypoetry/config.toml"

[river.files]
"config/river/init" = "~/.config/river/init"
"config/river/scripts" = {target="~/.config/river/scripts", type="symbolic", recurse=false}

[samba.files]
"config/samba/config.conf" = "/etc/samba/smb.conf"

[swaylock.files]
"config/swaylock/config" = "~/.config/swaylock/config"

[tofi.files]
"config/tofi/config.cfg" = "~/.config/tofi/config"
"config/tofi/scripts" = {target="~/.config/tofi/scripts", type="symbolic", recurse=false}

[tmux.files]
"config/tmux/config.tmux" = "~/.tmux.conf"
"config/tmux/silent-tmux.tmux" = "~/.silent-tmux.conf"

[waybar.files]
"config/waybar/config.json" = "~/.config/waybar/config"
"config/waybar/style.css" = "~/.config/waybar/style.css"

[winfetch.files]
"config/winfetch/config.ps1" = "~/.config/winfetch/config.ps1"

[wt.files]
"config/wt/config.json" = "~/scoop/persist/windows-terminal/settings/settings.json"
