# global config location for `dotter`
# maps the files in the git repo to where the system expects them to be

[bash.files]
"config/bash/config.sh" = "~/.bashrc"

[cava.files]
"config/cava/config.conf" = "~/.config/cava/config"

[dunst.files]
"config/dunst/config.conf" = "~/.config/dunst/dunstrc"

[foot.files]
"config/foot/config.ini" = "~/.config/foot/foot.ini"

[glaze-wm]
depends = ["git", "helix", "pwsh", "winfetch", "wt"]
[glaze-wm.files]
"config/glaze-wm/config.yaml" = "~/.glaze-wm/config.yaml"
"config/glaze-wm/scripts" = {target="~/.glaze-wm/scripts", type="symbolic", recurse=false}
"config/glaze-wm/autostart_wrapper.vbs" = "~/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/autostart_wrapper.vbs"
[glaze-wm.variables]
primary_monitor = 1

[git.files]
"config/git/config.ini" = "~/.gitconfig"
[git.variables]
autocrlf = "input"
gh_path = "/usr/bin/gh"

[grub.files]
"config/grub/grub" = "/etc/default/grub"

[helix.files]
"config/helix/config.toml" = "~/.config/helix/config.toml"
"config/helix/themes" = {target="~/.config/helix/themes", type="symbolic", recurse=false}
[helix.variables]
sh_cmd = "['bash']"

[hypr]
depends = ["bash", "dunst", "git", "helix", "kitty", "ly", "neofetch", "rofi", "swaylock", "tmux", "waybar"]
[hypr.files]
"config/hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"config/hypr/hyprempty.toml" = "~/.config/hypr-empty/config.toml"
"config/hypr/scripts" = {target="~/.config/hypr/scripts", type="symbolic", recurse=false}

[kanshi.files]
"config/kanshi/config" = "~/.config/kanshi/config"

[kitty.files]
"config/kitty/config.conf" = "~/.config/kitty/kitty.conf"

[ly.files]
"config/ly/config.ini" = "/etc/ly/config.ini"

[neofetch.files]
"config/neofetch/config.conf" = "~/.config/neofetch/config.conf"
[neofetch.variables]
disks = "'/boot/EFI' '/' '/home'"

[pwsh.files]
"config/pwsh/config.ps1" = "~/Documents/Powershell/Microsoft.Powershell_profile.ps1"  # doesn't work for roaming profiles

[pypoetry.files]
"config/pypoetry/config.toml" = "~/.config/pypoetry/config.toml"

[river]
depends = ["bash", "dunst", "foot", "git", "helix", "neofetch", "swaylock", "tofi", "tmux", "yambar"]
[river.files]
"config/river/init" = "~/.config/river/init"
"config/river/scripts" = {target="~/.config/river/scripts", type="symbolic", recurse=false}

[rofi.files]
"config/rofi/" = {target="~/.config/rofi", type="symbolic", recurse=false}

[spicetify.files]
"config/spicetify/config.ini" = "~/.config/spicetify/config-xpui.ini"
"config/spicetify/Themes" = {target="~/.config/spicetify/Themes", type="symbolic", recurse=false}
"config/spicetify/Extensions" = {target="~/.config/spicetify/Extensions", type="symbolic", recurse=false}
[spicetify.variables]
spotify_path = "/opt/spotify"
prefs_path = "~/.config/spotify/prefs"

[swaylock.files]
"config/swaylock/config" = "~/.config/swaylock/config"

[tofi.files]
"config/tofi/config.cfg" = "~/.config/tofi/config"
"config/tofi/scripts" = {target="~/.config/tofi/scripts", type="symbolic", recurse=false}

[tmux]
depends = ["bash", "git", "helix", "neofetch"]
[tmux.files]
"config/tmux/config.tmux" = "~/.tmux.conf"
"config/tmux/silent-tmux.tmux" = "~/.silent-tmux.conf"

[waybar.files]
"config/waybar/config.json" = "~/.config/waybar/config"
"config/waybar/style.css" = "~/.config/waybar/style.css"

[winfetch.files]
"config/winfetch/config.ps1" = "~/.config/winfetch/config.ps1"

[wt.files]
"config/wt/config.json" = "~/scoop/persist/windows-terminal/settings/settings.json"

[yambar.files]
"config/yambar/config.yml" = "~/.config/yambar/config.yml"
