includes = []
packages = [
  "wezterm", "bash", "fastfetch", "helix", "git", "pypoetry", "btop", "tmux"
]

[files]
"config/bash/tmux.sh" = "~/.bash/tmux.sh"
"config/bash/zoxide.sh" = "~/.bash/zoxide.sh"

[variables]
