includes = []
packages = [
  "wezterm", "bash", "fastfetch", "helix", "git", "pypoetry", "btop", "tmux",
  "mpd", "ncmpcpp", "rmpc"
]

[files]
"config/bash/tmux.sh" = "~/.bash/tmux.sh"
"config/bash/zoxide.sh" = "~/.bash/zoxide.sh"

[variables]
music_path = "~/syncthing/music"
