includes = [".dotter/include/windows.toml"]
packages = [
  "wezterm",
  "pwsh", "fastfetch", "mpd", "ncmpcpp",
  "helix", "git", "pypoetry", "btop"
]

[files]

[variables]
user_home = "c:/users/max"
music_path = "m:/"
