includes = []
packages = [
  "river", "foot", "waybar", "dunst", "swaylock", "kanshi", "tofi",
  "bash", "tmux", "neofetch", "gtk",
  "helix", "pypoetry", "git", "cava", "mpd", "ncmpcpp"
]

[files]

[variables]
disks = "'/boot/efi' '/' '/home' '/var/lib/lxd/storage-pools/default' '/vm' '/music' '/backup' '/dump'"
