includes = [".dotter/include/wsl.toml"]
packages = [
  "bash", "fastfetch", "tmux", "helix", "git", "ncmpcpp", "mpd", "cava"
]

[files]
"config/tmux/silent-tmux.tmux" = "~/.silent-tmux.conf"

[variables]
mpd_host = "127.0.0.1"
music_path = "/mnt/m"
