includes = [".dotter/include/windows.toml"]
packages = [
  "glaze-wm", "wt",
  "pwsh", "winfetch",
  "helix", "git", "mpd"
]

[files]

[variables]
disks = "'C:'"
mpd_host = "192.168.0.171"
music_path = "N:"
