includes = [".dotter/include/wsl.toml"]
packages = [
  "bash", "neofetch", "tmux",
  "helix", "git",
  "mpd", "ncmpcpp", "cava"
]

[files]

[variables]
mpd_host = "192.168.0.171"
music_path = "/mnt/n"
