#!/bin/sh
# Default rc.local for void; add your custom commands here.
#
# This is run by runit in stage 2 before the services are executed
# (see /etc/runit/2).

# force monitors ON
# causes slight problems, but at least windows don't rearrange themselves now
echo "on" > /sys/class/drm/card0-DP-1/status
echo "on" > /sys/class/drm/card0-DP-2/status

# setup macvtap network for qemu/kvm
#ip link add link eno1 name macvtap0 type macvtap mode bridge
#ip link set macvtap0 up

# setup bridged network for qemu/kvm
# https://www.spad.uk/posts/really-simple-network-bridging-with-qemu/
brctl addbr virtbr0
brctl addif virtbr0 enp3s0
ip addr add 192.168.0.22/24 dev virtbr0
ip link set virtbr0 up
iptables -I FORWARD -m physdev --physdev-is-bridged -j ACCEPT
iptables -I INPUT -p tcp --dport 6600 -j ACCEPT
